### ISSUE TITLE
Todo's

### ISSUE THREAD

**Issue by jaap** [frittsnl/sundata-metropolis-client-php#1]
### Versioning
- [x] Auto versioning

Versioning is implemented trough Github actions: https://github.com/anothrNick/github-tag-action

- [x] Default patch bump

When the commit message does not contain `#major` or `#minor` the patch value will be bumped (0.0.1 => 0.0.2)

### Removing unnecessary files from package
- [x] Remove assets in package (if possible)

Accomplished by adding `.gitattributes` which results in Github ignore certain files when generating a zip. On Github repo's composer always tries to get this package. So as long as the user is not requesting the 'git' version and uses a Composer default it seems to me that these assets wil be omitted.

### Webhook
- [x] Move satis build trigger to webhook instead of action (where it could be seen)

Resolved by adding a POST method to the build url for satis (https://github.com/frittsnl/satis/commit/53669747ff8fff11c06afd26932686c0730be54a) and adding a [webhook](https://github.com/frittsnl/sundata-metropolis-client-php/settings/hooks/266193730) to this repository.

### Git push shell command

- [ ] Make Git push more idiot proof

### Documentation

- [ ] Add instructions regarding generation of client
- [ ] Add instructions pushing new client to github
- [ ] Add regarding package release process (mainly versioning, webhook and package location)
